### ISSUE TITLE
schemaProperties does not work

### ISSUE THREAD

**Issue by uneco** [Mermade/openapi-codegen#10]
https://github.com/Mermade/openapi-codegen/blob/4e68a2699f0efe9aa87044636fa5843e5953124e/adaptor.js#L197

Test:
```js
for (let p in schemaProperties) {
    console.log('p:', p);
}
```

Output:
```
p: 0
p: 1
p: 2
p: 3
p: 4
p: 5
p: 6
p: 7
p: 8
p: 9
p: 10
p: 11
p: 12
p: 13
p: 14
p: 15
p: 16
```

use `of` instead of `in`?

**Comment by MikeRalphson** [comment]
Many thanks for reporting this, and the suggested fix. This has been included in v1.3.3
