### ISSUE TITLE
convert integer to number while generating typescript code.

### ISSUE THREAD

**Issue by sledorze** [Mermade/openapi-codegen#2]
Maybe a good solution would be to expose a mean to define some primitive types translations between openapi and the target language.

**Comment by MikeRalphson** [comment]
Great idea, thanks. I'm actually working on that right now! Will push what I've got. It seems to mainly pass the `tsc` compiler...

**Comment by MikeRalphson** [comment]
Improvements published as v1.1.1

**Comment by MikeRalphson** [comment]
> Shouldn't it be kept as 'array' it seems the mustache template has to handle the whole jsonschema definition:

```json
{
              "type": "array",
              "items": {
                "type": "string"
              }
}
```
> I guess what you've done is handy but if the upstream codegen project does not choose the same workaround then the mustache templates handling explicitely the array cases would not be compatibles.

**Comment by MikeRalphson** [comment]
Wow, that is an eye-aching amount of mustache 'logic' in your comment just to get a type. I wonder how we can help improve the situation, but not fragment the template authoring community? Is your project open source?

**Comment by sledorze** [comment]
@MikeRalphson Actually I'm building more than just the Typescript types; I'm also building io-ts schema definition (https://github.com/gcanti/io-ts).
That's where the automatic type spec falls short, on the other side, going through mustache, I cannot handle everything (e.g.: recursive types).

**Comment by MikeRalphson** [comment]
If you'd prefer to develop in Typescript/javascript rather than Java then I'd welcome PRs. We will need some kind of plugin system for custom code I'm sure.
