### ISSUE TITLE
RequestBody types

### ISSUE THREAD

**Issue by jonschoning** [Mermade/openapi-codegen#4]
What can we expect will be the plan for code generation, for the RequestBody for cases 1) and 2) below?

## 1) Multiple content-types with the same Schema
```
        "requestBody": {
          "description": "Pet object that needs to be added to the store",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            }
          },
          "required": false
        },
```
## 2) Multiple content-types with different Schemas

> Schemas can vary by media type.

 https://swagger.io/docs/specification/describing-request-body/
```
        "requestBody": {
          "description": "Pet object that needs to be added to the store",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Cat"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/Dog"
              }
            }
          },
          "required": false
        },
```
## 3) the AnyOf keyword

**Comment by MikeRalphson** [comment]
The primary goal will be to make the code-generation data model fit the current templates by faking a `bodyParam`, which will have a schema matching the first content-type from the OpenAPI 3 `requestBody`.

We will extend the data model with `.openapi` properties (i.e. the `operation` will have a `openapi.requestBody` property) and any convenience properties required by new / amended templates.

Use of `anyOf` etc will be driven by examples of the code which needs to be generated, then the data model will be extended to allow this to be expressed with templates.

These are my initial thoughts only, very happy to listen to all feedback.
