### ISSUE TITLE
Loading openapi-definition from Url is not possible

### ISSUE THREAD

**Issue by scipper** [Mermade/openapi-codegen#52]
The description on [npmjs.org](https://www.npmjs.com/package/openapi-codegen) says:

> You can also load the OpenAPI definition from a URL.

But it does not work, as the config file path always gets resolved:
 `53. let configFile = path.resolve(configPath,configName)+'.json';`

It would be nice, if definitions could be loaded by Url.

**Comment by MikeRalphson** [comment]
That's the configuration file, not the openapi definition...

**Comment by scipper** [comment]
but when I pass an Url, cg complains about a local file was not found like C:/project/http://some.url/swagger.json

**Comment by MikeRalphson** [comment]
Make sure that you have your `config` and `def` parameters round the right way.

**Comment by MikeRalphson** [comment]
Tested, this feature is definitely working correctly.
