### ISSUE TITLE
Add npx command to README

### ISSUE THREAD

**Issue by jaredpalmer** [Mermade/openapi-codegen#58]

**Comment by MikeRalphson** [comment]
Could you expand a little?

**Comment by jaredpalmer** [comment]
Instead of installing a package with globally `-g`, you can now use the `npx <package> <command>` to run npm packages that either live inside of a local node_modules folder or are not installed globally.

I think the following will work. You may need to change the name of the cli command to match the package name
```
npx openapi-codegen cg --verbose nodejs defs/generator.yaml
```



https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner

**Comment by MikeRalphson** [comment]
Done, thanks for the suggestion!
