### ISSUE TITLE
Error: Cannot find module '<currentpath>\configs\htmlDocs2.json

### ISSUE THREAD

**Issue by lagebaue** [Mermade/openapi-codegen#66]
I installed the package via npm and called it with
``cg htmlDocs2 docs/openapi.yaml``

But it fails to load the config file because it's looking relative to the current path instead of relative to the cg.js file (the require in cg.js:54)

How is this supposed to work? 

I assume this is because the path.resolve in [line 53](https://github.com/Mermade/openapi-codegen/blob/master/cg.js#L53) resolves ``./`` as cwd and not ``__dirname``. While the require would treat them as equal.

It would probably work just fine without the `path.resolve`. (just `path.join`, but then ofc paths relative to cwd would not work anymore...)

**Comment by MikeRalphson** [comment]
Sorry for the delay - if still an issue, can you confirm if you used `npm i --global` to install and what platform you're using?

**Comment by lagebaue** [comment]
Yes, global install on windows 7, node 10.15 run via git-bash

**Comment by MikeRalphson** [comment]
Should be fixed in v2.0.1 sorry for the wait.
