### ISSUE TITLE
Different template engine

### ISSUE THREAD

**Issue by iilyak** [Mermade/openapi-codegen#78]
I got that the main goal of this project is to be able to use unmodified templates from OpenAPITools project. However the mustache templates do not allow to control whitespace. I got a partial almost a thousand characters in length. Which makes it almost impossible to maintain if template itself is not indented. The usual workaround people use is to indent template for maintainability and then use code reformatting tools to remove extra lines from generated code. Unfortunately I work with the language which doesn't have good code reformatting tools which can spit the code using the code style of my project.

It would be nice if we could replace mustache with something else (I totally understand if we cannot). One of the options I know off is https://handlebarsjs.com/

**Comment by iilyak** [comment]
Actually according to https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0-rc0 the swagger-api switched to handlebarjs.

**Comment by MikeRalphson** [comment]
We use hogan.js here as it was the only js template engine which actually worked with the Swagger-Codegen 2.3 templates we imported.

See https://github.com/wycats/handlebars.js/blob/master/README.markdown#compatibility for a list of reasons why handebarsjs is not currently an option.

Maybe you could write a plugin for prettier or something for your target language?

Alternatively the new custom lambda support might help you refractor your templates.

**Comment by iilyak** [comment]
what if we would support both? We could choose the engine based on file extension. If it `.mustache` we would choose hogan. If it is `.hbr` we would select handlebars.

**Comment by MikeRalphson** [comment]
Can you point me to docs which confirm handlebars supports controlling whitespace?

**Comment by iilyak** [comment]
https://handlebarsjs.com/guide/expressions.html#whitespace-control

**Comment by iilyak** [comment]
Implementation wise it is quite easy. I patched openapi-codegen in few places and successfully using it in my project.

```
const Handlebars = require('handlebars');

....
Handlebars.registerHelper(lambda, generator.lambdas[lambda]);
....
Handlebars.registerPartial(p, ff.readFileSync(tpl(config, configName, partial),'utf8'));
...
let template = Handlebars.compile(action.template);
let content = template(model);
```

**Comment by iilyak** [comment]
I can do a PR if you think this feature is useful.

**Comment by MikeRalphson** [comment]
Are you in a position to also contribute a config and set of templates and a CI test, I.e. Will we have test coverage for this feature?

**Comment by iilyak** [comment]
I see two options here:
1. create configs/test-hbr.json and templates/test-hbr.hbr
2. create tests/fixtures/configs/test-hbr.json and  tests/fixtures/templates/test-hbr.hbr

The test can check that 
- the simple .hbr template rendered correctly
- the template in the filename of the target is rendered using engine depending on template file extension

**Comment by MikeRalphson** [comment]
I would prefer to only add the complexity of supporting multiple rendering engines if we can demonstrate a real-world set of templates that need the functionality. Happy to hear from anyone else who might need the functionality.

**Comment by MikeRalphson** [comment]
`v2.1.0` allows you to set a `generator` property with a `render` function in the config. See #118 for details.

**Comment by iilyak** [comment]
Thank you for merging the feature.
