### ISSUE TITLE
Possible to auto-populate examples object?

### ISSUE THREAD

**Issue by Asheq** [Mermade/openapi-codegen#8]
In the js files in the `impl` folder the examples objects are all empty.

Is there a way to auto-populate the examples the same way `swagger-codegen` does?

**Comment by MikeRalphson** [comment]
Should be possible to generate examples where not present in the source definition, using `openapi-sampler`. Thanks for the suggestion!

**Comment by MikeRalphson** [comment]
Version 1.4.0 has a step in this direction. It will need some further work for non-JSON content-types.
